safe:        true
auto:        false
server:      false
baseurl:     /

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount

source:      .
destination: ./_site
plugins:     ./_plugins

permalink: date

## Variables
title : Xi's
description : My place to think, to communicate, to learn. 
url : http://gshch.github.com
tagline : Xi
author : 
  name : Yanxi
  email : ye.gshch@gmail.com
  github : gshch
  twitter : 
  feedburner : 
  
production_url : http://gshch.github.com
